services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fastapi-mongo
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    links:
      - mongo
      - prometheus  # Añadir conexión con Prometheus

  mongo:
    image: mongo
    ports:
      - "5432:5432"
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"  # Puerto para acceder al dashboard de Prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus  # Volumen para persistir datos
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"  # Puerto para acceder a Grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=yourpassword
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  mongo-data:
  grafana-data:
  prometheus-data:  # Volumen persistente para Prometheus
