services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: fastapi-mongo
    ports:
      - "5001:5000"
    environment:
      - ENV=production
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - "5432:5432"
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
