global:
  scrape_interval: 5s   # Cada cuánto tiempo Prometheus recolecta métricas

scrape_configs:
  - job_name: "fastapi-api"  # Nombre que le das a este trabajo
    scrape_interval: 5s
    metrics_path: /metrics   # Ruta donde FastAPI expone las métricas
    static_configs:
      - targets: ['devops-project-1-m0rc.onrender.com']  # URL sin https:// de tu API en Render
