FROM grafana/grafana:latest

# Configura las credenciales predeterminadas
ENV GF_SECURITY_ADMIN_USER=admin
ENV GF_SECURITY_ADMIN_PASSWORD=yourpassword

# Exponer el puerto que usará Grafana
EXPOSE 3000