apiVersion: apps/v1
kind: Deployment
metadata:
  name: regression-model-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: regression-model
  template:
    metadata:
      labels:
        app: regression-model
    spec:
      containers:
      - name: regression-model-container
        image: regression-model   # Usamos la imagen local sin :latest
        imagePullPolicy: Never    # Le indicamos que no intente descargar la imagen
        ports:
        - containerPort: 8000
