name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    # Clonar el código desde el repositorio
    - name: Check out the repository
      uses: actions/checkout@v2

    # Loguearse en Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    # Construir la imagen de Docker desde la carpeta `docker/`
    - name: Build Docker image
      run: docker build -t zambrajose9/proyecto-devops:latest -f docker/Dockerfile .

    # Subir la imagen de Docker a Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push zambrajose9/proyecto-devops:latest