name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Clonar el código desde el repositorio
    - name: Check out the repository
      uses: actions/checkout@v2

    # Configurar Docker Buildx (requerido para ejecutar Docker en GitHub Actions)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Instalar Docker Compose (solución al problema actual)
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose version

    # Loguear en Docker Hub (opcional si quieres subir imágenes)
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    # Construir la imagen usando Docker Compose y levantar los contenedores
    - name: Build and Test Docker Compose
      run: |
        docker-compose up --build -d
        docker ps -a  # Verifica si los contenedores están corriendo

    # Probar la API FastAPI haciendo una solicitud HTTP
    - name: Run healthcheck
      run: |
        curl -f http://localhost:8000/docs || exit 1  # Verifica si la API está disponible

    # Apagar los servicios al final de la prueba
    - name: Tear down Docker Compose
      run: docker-compose down
