name: CI Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Actualizar a la versión más reciente de `actions/checkout`
    - name: Check out the repository
      uses: actions/checkout@v3

    # Actualizar a la versión más reciente de `docker/setup-buildx-action`
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Instalar Docker Compose
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose version

    # Construir la imagen usando Docker Compose y levantar los contenedores
    - name: Build and Test Docker Compose
      run: |
        docker-compose up --build -d
        docker ps -a  # Verifica si los contenedores están corriendo

    # Esperar a que la API esté disponible y probarla
    - name: Wait for API to start
      run: |
        sleep 10  # Esperar 10 segundos para que la API esté lista
        curl -f http://localhost:8000/docs || exit 1  # Verifica si la API está disponible
    
    # Ejecutar las pruebas unitarias con Pytest
    - name: Run unit tests
      run: |
        docker-compose exec app python -m pytest
        
    # Apagar los servicios al final de la prueba
    - name: Tear down Docker Compose
      run: docker-compose down
