name: CI Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build and Test Docker Compose
      run: |
        docker-compose up --build -d
        docker ps -a

    - name: Wait for API to start
      run: |
        for i in {1..30}; do
          echo "Waiting for API..."
          curl -f http://localhost:8080/docs || exit 1
          sleep 5
        done || exit 1

    - name: Run unit tests
      run: |
        docker-compose exec app python -m pytest

    - name: Tear down Docker Compose
      run: docker-compose down

    - name: Check Docker Logs (on failure)
      if: failure()
      run: |
        docker-compose ps
        docker-compose logs app
