name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose version

    - name: Build and Test Docker Compose
      run: |
        docker-compose up --build -d
        docker ps -a  # Verifica si los contenedores están corriendo

    - name: Check Docker Logs
      run: |
        docker-compose logs app

    - name: Wait for API to start (with retries)
      run: |
        for i in {1..10}; do
          if curl -f http://localhost:8000/docs; then
            echo "API is up!"
            exit 0
          fi
          echo "Waiting for API..."
          sleep 5
        done
        echo "API did not start in time!"
        exit 1

    - name: Run unit tests
      run: |
        docker-compose exec app python -m pytest

    - name: Tear down Docker Compose
      run: docker-compose down
